version: '2'
services:
  db:
    image: postgres:14
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo15      
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo15:
    image: odoo:15
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo15
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: always
    